version: "3"

services: 
  server:
    build: ./
    ports: 
      - "8080:8080"
    depends_on: 
      - db
      - redis
    container_name: backend
  
  db: 
    container_name: mysql
    image: mysql:8.0.11
    volumes:
      - "db_data:/var/lib/mysql"
    restart: always
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'trailblazer'
      MYSQL_DATABASE: 'animeApp'
  
  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379:6379

volumes:
  db_data: