version: "3.7"
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/animeApp.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: mysqladmin ping --user=$MYSQL_USER --password=$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 100
    environment:
      MYSQL_DATABASE: animeApp
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3306:3306"

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
  
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
  
  app:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data: {}