module.exports = {
  title: "Terms of Use",
  sections: [
    {
      title: "About Animei TV",
      description:`<a href="https://animei.tv">ANIMEI TV</a> is a highly comprehensive media and entertainment portal in <language> providing manga and anime video content to its users. The content provided on the website is an amalgamation of its own content and contents aggregated from media and entertainment websites. The content provided on Animei.tv pertains to, but is not limited to anime. Animei.tv is owned, promoted and managed by Animei TV Private Limited ("Company"). `
    },{
      title: "ACCEPTANCE OF TERMS",
      description: `Animeitv gives you royalty-free, non-assignable and non-exclusive license to use Animeitv’s website (www.Animei.tv). This license is for the sole purpose of enabling you to use and enjoy the benefits of the Services as provided by Animeitv, in the manner permitted by these terms. By using or accessing the website of Animeitv, you agree to abide by the terms of this Agreement. This is an agreement between you and Animeitv that describes your rights to use Animeitv’s website as specified in the Agreement and as modified by Animeitv from time to time. In case you choose not to agree with this Agreement, you may not use the Services of Animeitv.`
    },{
      title: "DESCRIPTION OF SERVICES",
      description: `Animeitv provides its users an automated portal for access into various anime-based content, communication tools, personalised services through its network (the "Services"). You also understand and agree that the Services may include certain communications from Animeitv, including, on your social media platforms and that these communications are considered as part of the Services of Animei and you cannot opt out of it. You agree that any change or update in Animeitv’s current Services shall be subject to terms of this Agreement. You understand and agree that Animeitv assumes no responsibility for mis-delivery or failure to deliver these Services.
      You acknowledge that the Services of Animeitv are available only via third party channels. You also acknowledge that we are not responsible or liable in any way for your access to the Services or your use of any third-party channels through Animeitv. You acknowledge that you are solely responsible for the set-up, configuration or compatibility of the hardware, software and other equipment including payment (if applicable) for obtaining access to the any such third-party channels.
     In all cases, your correspondence or business dealings with, or participation in promotions of other parties are found through the Services, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third party, even where it is in relation to any products or services that are co-branded with Animeitv. You agree that we shall not be responsible or liable in any way for any loss or damage of any sort incurred as the result of any such dealings with any third parties.`
    },{
      title: "THIRD-PARTY CONTENT",
      description: `Animeitv is an automated portal which indexes third party websites and do not have control over, nor have any liability for any information, data, text, software, music, sound, photographs, graphics, video, messages or other materials ("Content") of such third-party websites. Animeitv only uses an automated technology to crawl the third-party websites and do not in any manner infringe on rights of any site. Animeitv do not endorse any third-party websites, their content, products or services. 
      Results which are visible on our website may be served as a crawled result, where the actual content ownership and/or broadcasting permission lies with the respective website and not with Animeitv. Animeitv does not provide any downloading services on the website. Animeitv is not responsible for the availability of such external sites or resources and is not responsible or liable for any Content, advertising, products, or other materials on or available from such sites or resources. Links of third-party websites which provide illegal, obscene or objectionable content under the prevailing law, is strictly forbidden on the Animei.tv. Though Animeitv exercises due diligence to observe that any such third-party links are removed, you may make Animeitv aware of such links that lead to objectionable content, if you come across while using the service. You further acknowledge and agree that Animeitv shall not be responsible or liable, in any manner whatsoever, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site.`
    },{
      title: "USER OBLIGATIONS FOR UPLOADING CONTENT",
      description: `Some of our Services allow you to upload, submit, store, send or receive content. You understand and acknowledge that any Content, whether publicly posted or privately transmitted, are the sole liability of the person from whom such Content is devised. You shall have the entire liability for all Content that you upload, post or otherwise transfer via the Service. Under no situations will Animeitv or its affiliates, officers, agents or employees, be liable in any way for any Content, including offensive, indecent or objectionable Content. 
      You warrant that you shall not host, display, upload, modify, publish, transmit, update or share any information that-
      belongs to another person and to which the user does not have any right to; 
      is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; 
      harm minors in any way; 
      infringes any patent, trademark, copyright or other proprietary rights; 
      violates any law for the time being in force; 
      deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; 
      impersonate another person; 
       contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; 
      threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
      Animeitv exercises due diligence to safeguard that any such content are removed. You may make Animeitv aware of such objectionable content as mentioned above, if you come across while using the service.
      When you upload, submit, store, send content to or through our Services, you give Animeitv and its affiliates a worldwide license to use, host, store, reproduce, modify, create derivative works, communicate, publish, publicly perform, publicly display and distribute such content.
      `
    },{
      title: "SUBSCRIPTION SERVICES",
      description: `Some of the Content made available on the Site can be availed only by registered Users who have registered under a subscription model ("Subscription User"). You may need to register Yourself on the Site to avail these services on a subscription model ("Subscription"). To become a Subscription User, You may be required to provide certain personal information to Animeitv and may be required to make payments ("Subscription Fee") as per the applicable membership plan through a debit card, credit card, internet banking or through, e- prepaid wallet or other payment method accepted by Animeitv ("Payment Method(s)") that You opted for during registration. Animeitv will be using third party payment gateways to process and facilitate the payment of Your Subscription Fee to Animeitv. For Premium Subscription proposed to be activated through Your registered mobile number, in addition to the above Payment Methods, cash on delivery payment option would be available to You, subject to the terms and conditions set out herein. On successful registration to the Subscription, Animeitv will intimate You of the same. Animeitv may offer different kinds of Subscription plans, each of these Subscription plans will be subject to different limitations and restrictions and the cost of each of these Subscription plans may vary. You may choose more than 1 Subscription plan during a given period.
      Animeitv currently offers viewers the following Subscription plans to choose from:
      (1) all access premium subscription pack, and
      (2) limited subscription packs with full access to certain Content, including Disney+ Hotstar VIP. 
      Animeitv shall have the discretion to make certain Content that is a part of the Subscription available to You on more than one end user Compatible System concurrently. Animeitv shall also have the discretion to make certain Content that is a part of the Subscription available to You on not more than one end user device concurrently.
       Any personal data whether provided by you as a part of the Subscription registration process, or collected automatically when you use the Service will be governed by the Privacy Notice accessible at< Link> 
      `
    },{
      title: "FREE TRIAL",
      description: `Some of the Subscription plans may start with a free trial. The free trial period may last for a period of one month or such other term as may be determined by Animeitv. Your eligibility for a free trial including the time for such free trial and the Content available to be viewed during free trial period is at the discretion of Animeitv and such free trial can be modified, suspended or terminated by Animeitv at any point of time without giving notice to You.;
      In case You are eligible for any free trial, Animeitv may charge You a token amount of money at the time of Your registration for a Subscription plan. This token amount will be refunded to You once Animeitv receives the confirmation from the third-party payment gateway provider that Your Payment Method has been registered.
     `
    },{
      title: "PAYMENTS",
      description: `Animeitv will automatically start billing as per Your selected Payment Method for the relevant Subscription plan(s) selected by You at the time of registration through the third party payment gateway at the end of the free trial period, if applicable unless You cancel a Subscription(s) before the end of the free trial period. The cancellation of a Subscription can be done through the "My Account" section of the Site. It may take a few days for Your payment made to Animeitv to be reflected in your "My Account" section.
      In case You cancel any Subscription before the end of the free trial period, You will not be entitled to any compensation monetary or otherwise from Animeitv for the unutilized period of free trial.
      You cannot change your Payment Method during the tenure of your Subscription(s). If Your selected Payment Method is no longer available or expires or Your Payment Method fails for whatsoever reason, You will be responsible and liable for any uncollected amounts and Animeitv reserves the right to terminate the Subscription(s) offered to You.
      The Subscription Fee for a particular Subscription will be billed at the beginning of the Subscription membership or at the end of free trial period, as applicable and on each subsequent renewal automatically (as per the Subscription plan chosen by You) unless and until You cancel Your Subscription(s) or the Subscription(s) is otherwise suspended or discontinued pursuant to these Terms. To see the commencement date for Your next renewal period or to cancel Your subscription to the Subscription(s), You need to visit the "My Account" section on Your profile page. On cancellation of a Subscription(s) You will be notified by Animeitv.
      Animeitv will be automatically billing as per Your Payment Method for each Subscription period on a monthly basis. However, if You change Your membership plan, this could result in changing the day on which You are billed and the amount which You are billed. Further, on changing your existing Subscription plan to another, you would be required to pay the difference in rates (on a pro rata basis) for the new Subscription plan selected and would be billed as per the new Subscription plan from the next billing / renewal cycle. In case the rate for the new Subscription plan is less than that of the existing Subscription plan, the difference in rates would be adjusted (on a pro rata basis) and you will be billed accordingly from the next billing / renewal cycle. Animeitv will notify you in advance of the change in the Subscription Fee payable.
      The new Subscription will be effective from the date on which you select such plan and make appropriate payments as necessary.
      In case of change in the Subscription Fee for a particular membership plan that is already opted by You, Animeitv will give You an advance notice of these changes.
      The Subscription Fees specified for each Subscription plan are inclusive of applicable taxes.
      The Subscription Fees billed are non-refundable irrespective of whether the Subscription have been availed by You or not.
      Any request for change or cancellation in any Subscription plan prior to the expiration of the current Subscription plan period will not entail You with a refund for any portion of the Subscription Fee paid by You for the unexpired period.
      You also understand and acknowledge that Animeitv only facilitates the third-party payment gateway for processing of payments. This facility is managed by the third-party payment gateway provider and You are required to follow all the terms and conditions of such third-party payment gateway provider.
      You are responsible for the accuracy and authenticity of the payment information provided by You, including the bank account number/credit card details and any other information requested during the subscription process. You represent and warrant that you have the right to use any credit card or other payment information that you submit. You agree and acknowledge that Animeitv shall not be liable and in no way be held responsible for any losses whatsoever, whether direct, indirect, incidental or consequential, including without limitation any losses due to delay in processing of payment instruction or any credit card fraud.
      You can access the status of Your Subscription anytime through the "My Account" section on Your profile page.You can file any complaint related to payment processing on the Site and the same will be forwarded to the concerned third-party payment gateway provider for redressal.
     Upon payment through any of the Payment Modes and confirmation of receipt of such payment from the payment gateway provider, an invoice will be made available to You in the "MY Account" section which can be downloaded by You in pdf format. Upon payment being received by Animeitv through any of the Payment Method, Animeitv shall make the relevant Subscription available to You through any of the approved modes of delivery that Animeitv adopts.It is hereby clarified that the Subscription(s) offered to You are offered by Animeitv and not by any third party including any payment gateway service providers.
     Animeitv reserves the right to change, terminate or otherwise amend the Subscription plans, Subscription Fees for the Subscription and billing cycles at its sole discretion and at any time. Such amendments shall be effective upon posting on the Site and Your continued use of the Service shall be deemed to be Your conclusive acceptance of such amendments.
      Animeitv reserves the right to change, supplement, alter or remove any of the Content that is subject to a Subscription Fee as it deems fit. Animeitv does not guarantee the availability of a specific Content or a minimum Content that is subject to a Subscription Fee. Post cancellation of Your Subscription, if you wish to re-subscribe to the Subscription, you may do so from Your "My Account" page.
     `
    },{
      title: "ACCESSING THE SERVICE THROUGH VPN",
      description: `You should not access or use the Service or the content therein by means of any mechanism or technology which conceals your actual geo-location or provides incorrect details of your location (for example, use a virtual private network (VPN)). 
      `
    },{
      title: "TERMINATION OF SERVICE",
      description: `Animeitv reserves the right to immediately terminate, suspend, limit, or restrict Your account or Your use of the Services or access to Content at any time, without notice or liability, if Animeitv so determines in its sole discretion, for any reason whatsoever, including that You have breached these Terms and Conditions, the Privacy Policy, violated any law, rule, or regulation, engaged in any inappropriate conduct, provided false or inaccurate information, or for any other reason. You hereby agree and consent to the above and agree and acknowledge that Animeitv can, at its sole discretion, exercise its right in relation to any or all of the above, and that Animeitv, its directors, officers, employees, affiliates, agents, contractors, principals or licensors shall not be liable in any manner for the same; and You hereby agree, acknowledge and consent to the same. You hereby also agree that Animeitv shall not refund any amounts that you may have paid to access and/or use the Services.`
    },{
      title: "ADVERTISING",
      description: `Animeitv expressly disclaim any liability arising out of the advertisements, usage or viewing of these products or services advertised on our Site or the (third party) content made available / hosted on the third-party sites.
      Animeitv takes no responsibility for advertisements or any third-party material posted on the Site nor does it take any responsibility for the products or services provided by advertisers. Any dealings You have with advertisers found while using the Services are between You and the advertiser, and You agree that Animeitv is not liable for any loss or claim that You may have against an advertiser.
      `
    },{
      title: "INDEMNIFICATION ",
      description: `You release Animeitv from, and agree to indemnify, defend and hold harmless Animeitv (and its officers, directors, employees, agents, vendors,  and Affiliates) against, any claim, loss, damage, settlement, cost, taxes, expense or other liability (including, without limitation, attorneys' fees) (each, a "Claim") arising from or related to: (a) your actual or alleged breach of any obligations in this Agreement; (b) Claims made by any third party due to your use of the Services of Animeitv or arising out of Content you submit, post to or transmit or make available through the Service, any actual or alleged infringement of any Intellectual Property Rights, and any personal injury, death or property damage related thereto.  In any adversely affecting claim, Animeitv may take exclusive control of the defence. You may not consent to the entry of any judgment or enter into any settlement of a Claim without our prior written consent, which may not be unreasonably withheld.
      `
    },{
      title: "PRIVACY POLICY",
      description: `Animeitv may collect many kinds of information in order to operate effectively and provide you with optimum services and experiences.  Animeitv’s privacy policies explains how your personal data and privacy will be protected when you use our Services. By using our Services, you agree that Animeitv can use such data in accordance with our privacy policies. Our Privacy policy could be accessed at ______`
    },{
      title: "DISCLAIMER ",
      description: `THE ANIMEITV SITE AND THE SERVICES, INCLUDING ALL CONTENT, SOFTWARE, FUNCTIONS, MATERIALS AND INFORMATION AVAILABLE OR PROVIDED IN CONNECTION WITH THE SERVICES, ARE PROVIDED "AS-IS." AS A USER OF THE SERVICES, YOU ACCESS THE ANIMEITV SITE, THE SERVICES AND ANY ONLINE PORTAL OR TOOL PROVIDED BY ANIMEITV TO HELP YOU AVAIL THE SERVICES AT YOUR OWN RISK. ANIMEITV AND ITS AFFILIATES WAIVE AND DISCLAIM: (1) ANY REPRESENTATIONS, WARRANTIES, DECLARATIONS OR GUARANTEES REGARDING THIS AGREEMENT, THE SERVICES OR THE TRANSACTIONS CONTEMPLATED WITH ANY THIR-PARTY, INCLUDING ANY IMPLIED WARRANTIES, DECLARATIONS OR GUARANTEES, FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT; (2) IMPLIED WARRANTIES ARISING OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE; AND (3) ANY OBLIGATION, LIABILITY, RIGHT, CLAIM OR REMEDY IN TORT, WHETHER OR NOT ARISING FROM OUR NEGLIGENCE OR CONTENT INCLUDING THIRD-PARTY CONTENT. WE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE ANIMEITV SITE OR THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE, TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE, AND WE WILL NOT BE LIABLE FOR ANY SERVICE INTERRUPTIONS.
      BECAUSE ANIMEITV IS AN AUTOMATED PORTAL WHICH INDEXES THIRD PARTY WEBSITES, IF A DISPUTE ARISES BETWEEN USER AND ANY SUCH THIRD PARTY, YOU AGREE TO RELEASE ANIMEITV (AND ITS AGENTS, AFFILIATES AND EMPLOYEES) FROM CLAIMS, DEMANDS, AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.
      `
    },{
      title: "LIMITATION OF LIABILITY ",
      description: `ANIMEITV WILL NOT BE LIABLE (WHETHER IN CONTRACT, WARRANTY, TORT, INCLUDING NEGLIGENCE, PRODUCT LIABILITY, ANY TYPE OF CIVIL RESPONSIBILITY OR OTHERWISE) TO YOU OR ANY OTHER PERSON FOR COST OF COVER, RECOVERY OR RECOUPMENT OF ANY DAMAGES IN CONNECTION WITH THIS AGREEMENT OR BY USING OUR SERVICES INCLUDING PUNITIVE OR CONSEQUENTIAL DAMAGES.`
    },{
      title: "NOTICE",
      description: `Notices to you may be made via display of notices or links to notices generally on Animeitv’s website and the same will constitute sufficient and adequate notice to you of the matters contained therein.`
    },{
      title: "TRADEMARK INFORMATION",
      description: `You agree that without Animeitv's prior permission, you shall not to display or use in any manner Animeitv’s trademark, logos and brand features.
      `
    },{
      title: "MISCELLANEOUS ",
      description: `This Agreement will be governed by the laws of India. You hereby irrevocably consent to the exclusive jurisdiction and venue of the courts at ______ regarding any dispute with Animeitv relating in any way to this Agreement or your use of the Services. This Agreement will be binding on, inure to, and be enforceable against you and your respective successors and assigns. Animeitv may perform any of the obligations or exercise any of our rights under this Agreement through one or more of our Affiliates. Our failure to enforce your strict performance of any provision of this Agreement will not constitute a waiver of our right to enforce such provision or any other provision of this Agreement subsequently. `
    },{
      title: "REACHING US",
      description: `You can reach Animeitv for any notice, information, grievance, complaints at:
      ANIMEI TV PRIVATE LIMITED, 
      _____________________
      Email:____________, Phone: ______________
      `
    }
  ]
}